In [1]:
import numpy as np
@np.vectorize
def convertor(arr):
    return (arr-32)*(5/9)
f_t=np.array([32, 68, 100, 212, 77])
c_t=convertor(f_t)    
c_t

array([  0.        ,  20.        ,  37.77777778, 100.        ,
        25.        ])

In [2]:
@np.vectorize
def custom_f(base, exponent):
    return base ** exponent

numbers=np.array([2, 3, 4, 5])
power=np.array([1, 2, 3, 4])
result=custom_f(numbers, power)
print(f'Result: {result}')



Result: [  2   9  64 625]


In [3]:
w=np.array([
    [4, 5, 6], 
    [3,-1,1],
    [2,1, -2]
])

z=np.array([7, 4, 5])
np.linalg.solve(w, z)

array([ 1.7027027 ,  0.62162162, -0.48648649])

In [4]:
q=np.array([
    [10, -2, 3], 
    [-2,8,-1],
    [3,-1, 6]
])
r=np.array([12, -5, 15])
np.linalg.solve(q, r)

array([ 0.48963731, -0.2253886 ,  2.21761658])

In [5]:
from PIL import Image

# Load and display image
image = Image.open('me1.jpg')
arr_img=np.array(image)
arr_img

array([[[ 61,  48, 104],
        [ 73,  52, 111],
        [ 53,  14,  77],
        ...,
        [  0,  37,  79],
        [ 19,  68, 109],
        [  7,  46, 103]],

       [[ 91,  76, 133],
        [ 93,  72, 131],
        [120,  84, 146],
        ...,
        [ 49,  76, 119],
        [ 53,  92, 135],
        [ 10,  47, 100]],

       [[ 83,  63, 122],
        [104,  80, 140],
        [124,  93, 153],
        ...,
        [ 69,  75, 125],
        [ 39,  57, 105],
        [ 22,  56, 104]],

       ...,

       [[ 72,  67, 108],
        [ 41,  34,  75],
        [ 61,  46,  85],
        ...,
        [ 18,  15,  32],
        [ 13,  18,  22],
        [  0,   9,  18]],

       [[ 24,  23,  63],
        [ 18,  13,  53],
        [ 54,  42,  80],
        ...,
        [ 11,   9,  23],
        [  0,   0,   4],
        [ 37,  32,  38]],

       [[ 30,  34,  72],
        [ 72,  72, 110],
        [ 37,  27,  64],
        ...,
        [ 10,   9,  23],
        [  2,   0,   1],
        [ 31,  12,  14]]

In [6]:
import numpy as np
from PIL import Image


reverse = arr_img[:, ::-1, :]  

reverse_pil = Image.fromarray(reverse)
reverse_pil.save('reverse_image.jpg')  

In [7]:
up_to_down=arr_img[::-1, :, :]
up_to_down_pil=Image.fromarray(up_to_down)
up_to_down_pil.save('up_to_dwon.jpg')

In [8]:
import numpy as np
from PIL import Image

noise=np.random.randint(0, 40, arr_img.shape, dtype='uint8')
noise_adj=np.clip(arr_img+noise, 0, 255)
noise_img=Image.fromarray(noise_adj.astype('uint8'))
noise_img.save('noisy_image.jpg')

In [9]:
import numpy as np
from PIL import Image


a0, a1 = 100, 200
b0, b1 = 100, 200


modified_img = arr_img.copy()


modified_img[a0:a1, b0:b1, :] = [0, 0, 0]  


modified_pil = Image.fromarray(modified_img)
modified_pil.save('cropped_black_region.jpg')

