In [3]:
import numpy as np
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [8]:
np.array([[0, 1, 2], 
         [3, 4, 5],
         [6, 7 ,8 ]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
import numpy as np
matrix=np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
import random

np.random.randint(0,1000, size=(3, 3, 3))


array([[[435, 517, 798],
        [725, 425, 817],
        [896,  74, 768]],

       [[648, 585, 820],
        [816, 683, 486],
        [251,   0, 182]],

       [[933,  75, 492],
        [695, 355, 906],
        [947, 838, 812]]])

In [31]:
np.random.randint(0, 1000, size=(10, 10)).max()

np.int64(996)

In [5]:
a=np.random.randint(0, 100, size=(3, 10))
a.mean()






np.float64(48.96666666666667)

In [44]:
matrix=np.random.randint(0, 100, size=(5, 5))
normalized_matrix=(matrix-matrix.min())/(matrix.max()-matrix.min())
print(f'Original matrix is {matrix}')
print(f'Normalized matriz is {normalized_matrix}')

Original matrix is [[48 96 57 33 94]
 [57 82 79 70 18]
 [52 28 92 44  6]
 [56 59 83 77 95]
 [47 17 35 49 44]]
Normalized matriz is [[0.46666667 1.         0.56666667 0.3        0.97777778]
 [0.56666667 0.84444444 0.81111111 0.71111111 0.13333333]
 [0.51111111 0.24444444 0.95555556 0.42222222 0.        ]
 [0.55555556 0.58888889 0.85555556 0.78888889 0.98888889]
 [0.45555556 0.12222222 0.32222222 0.47777778 0.42222222]]


In [48]:
matrix1=np.random.randint(0,10, size=(5, 3))
matrix2=np.random.randint(0,10, size=(3, 2))
multply=matrix1 @ matrix2
multply

array([[ 27,  21],
       [ 75,  86],
       [ 42,  31],
       [108,  97],
       [107, 121]])

In [ ]:
mat=np.random.rand(3,3)*100
mat1=np.random.rand(3, 3)*100

hey=mat @ mat1
hey

array([[ 9137.0881374 ,  7539.45214393,  5221.11465524],
       [ 6295.49362587,  7138.40646028,  6058.61653743],
       [11335.04957144,  5221.37723101,  4474.35351222]])

In [53]:
mat=np.random.rand(4, 4)*100
bay=mat.transpose()
bay

array([[92.46147528, 28.16018057, 39.65186306,  9.03157129],
       [46.53228215,  6.00640768, 95.9190773 , 79.91342674],
       [46.71500317, 45.17762519, 37.43209572, 57.62271545],
       [57.98519268, 17.24409689, 75.20556718, 75.67956574]])

In [4]:
mat=np.random.rand(3, 3)*100
det=np.linalg.det(mat)
det

np.float64(-28742.629109684964)

In [55]:
tur=np.random.rand(4, 3)*50
hrr=np.random.rand(3, 4)*32
sur=hrr @ tur
sur

array([[1278.99372913, 1437.62247231, 2089.55829309],
       [1470.35501017, 1894.03818986, 2641.79790029],
       [2299.30854025, 1938.76790129, 2690.98549846]])

In [58]:
mat
bore=np.array([1, 2,3])
der=mat* bore
der

array([[ 41.39829753,   5.81380108, 282.40346061],
       [ 96.08115787,  63.58833473, 229.43447363],
       [ 24.87371102, 190.87100367, 259.89578599]])

In [ ]:
linear=bore/der
linear


array([[0.02415558, 0.34400902, 0.0106231 ],
       [0.01040787, 0.03145231, 0.01307563],
       [0.04020309, 0.01047828, 0.01154309]])

In [ ]:
pish=np.random.rand(5, 5)*33


array([[ 5.00413428,  0.88914506, 14.90048776,  7.1727197 , 27.31713548],
       [24.13568018, 10.78880816, 30.97770483, 10.21779969, 18.07261394],
       [26.61983969, 11.41650533,  1.08835818, 31.82415174, 18.14609759],
       [ 9.05865649, 25.90786431, 13.84142138, 12.6259823 , 17.75534087],
       [15.53536927,  3.39918546, 16.27476522, 27.26344848, 13.55240595]])

In [74]:
a=pish[0].sum()
b=pish[1].sum()
c=pish[2].sum()
d=pish[3].sum()
r=pish[4].sum()
print(f'column_wise sums:\n {a},\n {b},\n {c},\n {d},\n {r}')

column_wise sums:
 55.283622277191924,
 94.19260681044723,
 89.09495253375923,
 79.18926534819592,
 76.02517437819954


In [85]:
q=pish[0:5, 0].sum()
w=pish[0:5, 1].sum()
e=pish[0:5, 2].sum()
t=pish[0:5, 3].sum()
u=pish[0:5, 4].sum()
print(f'Row-wise sums:\n{q},\n{w},\n{e},\n{t},\n{u}')


Row-wise sums:
80.35367990834803,
52.40150833261812,
77.08273736575654,
89.10410191157203,
94.84359382949908
